Sprint 10
vikhlyaev/ImageFeed pull request #3
Opened 2023-03-28 08:59 UTC by vikhlyaev

2023-04-05 18:45 UTC, vikhlyaev commented
Я могу добавить константы в .gitignore? 
Или они необходимы для проверки?

2023-04-05 20:31 UTC, mmbabaev requested changes

2023-04-05 20:31 UTC, mmbabaev commented on ImageFeed.xcodeproj/project.pbxproj
> +		0A714C0E29DD96A0007D76C5 /* OAuthTokenResponseBody.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; name = OAuthTokenResponseBody.swift; path = ../../../../.Trash/ImageFeed
вот здесь видно, что проект ссылается на файл, расположенный физически в корзине. 

Из-за этого проект не компилируется

2023-04-05 20:31 UTC, mmbabaev commented on ImageFeed/Services/OAuthService.swift
> +        URLSession.shared.dataTask(with: request) { data, response, error in
предлагаю сделать `URLSession.shared` свойством класса, а еще лучше передавать через init. Так будет возможность подменить реализацию и мы явно показываем зависимости класса

2023-04-05 20:31 UTC, mmbabaev commented on ImageFeed/Services/OAuthService.swift
> +                    let decoder = JSONDecoder()
то же самое с decoder, но некритично

2023-04-05 20:31 UTC, mmbabaev commented on ImageFeed/Screens/Splash/SplashViewController.swift
> +                break
тут ошибка "проглатывается", можно как-то обработать ее

2023-04-06 17:19 UTC, mmbabaev approved these changes

2023-04-06 17:19 UTC, mmbabaev commented on ImageFeed/Screens/Auth/WebViewViewController.swift
> +    private func setDelegates() {
лучше setWebViewDelegate, потому что у WebViewViewController есть уже свой делегат

2023-04-06 17:19 UTC, mmbabaev commented on ImageFeed/Screens/Auth/WebViewViewController.swift
> +    private func setDelegates() {
еще можно просто WebViewController

2023-04-06 17:19 UTC, mmbabaev commented on ImageFeed/Screens/Splash/SplashViewController.swift
> +                // временный принт
можно еще использовать шаблон TODO: 

```
// TODO: обработать ошибку
```

2023-04-07 13:42 UTC, merged