Sprint 11
vikhlyaev/ImageFeed pull request #4
Opened 2023-04-10 17:08 UTC by vikhlyaev

2023-04-12 03:12 UTC, mmbabaev commented
<img width="481" alt="Screenshot 2023-04-12 at 06 10 56" src="https://user-images.githubusercontent.com/12600807/231338707-64caf0e3-3af2-4a1f-b5a5-875ea1a8ec22.png">
Сейчас Main.storyboard указан как стартовая точка приложения, поэтому появляется ошибка в консоли. Это можно поправить, убрав это значение

2023-04-12 19:42 UTC, mmbabaev commented
Сейчас отображается ошибка 422, скорее всего неправильно заданы константы
<img width="508" alt="Screenshot 2023-04-12 at 22 41 41" src="https://user-images.githubusercontent.com/12600807/231567354-8e525a3e-9deb-4978-909b-9d3fd5a0be49.png">

2023-04-12 19:43 UTC, mmbabaev requested changes

2023-04-12 19:43 UTC, mmbabaev commented on ImageFeed/Screens/Splash/SplashViewController.swift
> +import ProgressHUD
этот импорт вроде не нужен

2023-04-12 19:43 UTC, mmbabaev commented on ImageFeed/Screens/Splash/SplashViewController.swift
> +                ProfileImageService.shared.fetchProfileImageURL(username: profile.username) { _ in }
лучше сервис тоже вынести в свойство

2023-04-13 03:58 UTC, vikhlyaev commented
> Сейчас отображается ошибка 422, скорее всего неправильно заданы константы
> <img alt="Screenshot 2023-04-12 at 22 41 41" width="508" src="https://user-images.githubusercontent.com/12600807/231567354-8e525a3e-9deb-4978-909b-9d3fd5a0be49.png">

2023-04-13 04:00 UTC, vikhlyaev commented
> Сейчас отображается ошибка 422, скорее всего неправильно заданы константы
> <img alt="Screenshot 2023-04-12 at 22 41 41" width="508" src="https://user-images.githubusercontent.com/12600807/231567354-8e525a3e-9deb-4978-909b-9d3fd5a0be49.png">

Этот вопрос решен в последнем коммите. Проблема была в том, что я зачем-то поставил POST в реквесте.

2023-04-14 22:01 UTC, mmbabaev requested changes

2023-04-14 22:01 UTC, mmbabaev commented on ImageFeed/Extensions/URLSession + Extensions.swift
> +                    if let object = try? decoder.decode(T.self, from: data) {
здесь происходит "проглатывание" ошибки парсинга данных. Если данные не распарсились, то completion не вызывается. Это нужно исправить, вызывать completion с ошибкой

2023-04-14 22:01 UTC, mmbabaev commented on ImageFeed/Models/Decodable/ProfileResult.swift
> +    let lastName: String
это поле опциональное, оно может прийти как null, его нужно сделать `String?`, как bio ниже

2023-04-16 19:17 UTC, mmbabaev approved these changes

2023-04-16 19:17 UTC, mmbabaev commented on ImageFeed/Extensions/URLSession + Extensions.swift
> +                        completion(.failure(NetworkError.parsingJsonError))
можно сделать associatedValue, аналогично `NetworkError.urlRequestError` и передавать туда ошибку, которая выбрасывается при `decode`

2023-04-16 19:17 UTC, mmbabaev commented on ImageFeed/Services/ProfileService.swift
> +                сompletionOnMainQueue(.success(profile))
обычно когда делают completion кложуры, то их вызывают именно в конце функции. Клиент кода может неправильно использовать функцию, например, прочитать в completion `service.profile`, который еще не переставился

2023-04-17 03:38 UTC, merged